### ISSUE TITLE
OpenMolcas DMRGSCF starting orbitals

### ISSUE THREAD

**Issue by wjc404** [qcscine/qcmaquis#14]
I have a few questions about the starting orbitals of active space.
(1) Do we need to localize active orbitals (explicitly) prior to DMRGSCF calculations (e.g. using the LOCALISATION program in OpenMolcas)? In the manual of the ORCA program (which uses BLOCK as the DMRG solver), it is stated that orbital localization will help improving the result.
(2) What about the initial ordering of active orbitals (or sites) when symmetry is turned on? In OpenMolcas the molecular orbitals are usually grouped by symmetry, orbitals having the same symmetry are put together(i.e. sorted first by symmetry then by energy). Will this ordering be preserved when entering DMRG iterations?

**Comment by stknecht** [comment]
hi,
to 1) orbital localisation may help in the initial DMRGSCF (and subsequent) iteration(s) but it is not mandatory. Since the SCF step within the DMRGSCF framework will rotate the orbitals, one is not guaranteed to stay within a local(ized) basis.
to 2) yes, the ordering of the orbitals will follow the OpenMolcas one unless you change the order explicitly by means of the 
```
orbital_order = "..."
```
keyword within the DMRG input block.

**Comment by wjc404** [comment]
Thanks for your help.
