### ISSUE TITLE
Clarification on RDMs storage

### ISSUE THREAD

**Issue by i-gianni** [qcscine/qcmaquis#16]
Thanks to whoever will answer to this.

I am trying to use QCMaquis as a CASCI solver to interface with a CASSCF algorithm. To do so, I need to extract the 1- and 2-body RDMs from the result file.
I would like to ask for clarification on how the RDMs are stored as none of the dimensions fit with the actual number of orbitals passed. I suppose that the "labels_num" array contains two columns corresponding to alpha and beta spinorbitals, but I can't find on any QCMaquis manual what the number of rows corresponds to. 
I would really appreciate a clarification. Thank you so much!

P.S.: I would kindly suggest to add a warning when a keyword from the input file is not recognized.

**Comment by i-gianni** [comment]
I managed to understand it myself. Thanks anyway.

**Comment by mmoerchen** [comment]
Hi,

sorry for the late reply.
In order to store the RDMs more efficiently, we only store non-zero entries and the corresponding indices.
We are currently working on python-bindings, to include QCMaquis also in existing Python-based workflows.

We are aware on the potential problems regarding the keywords from the input file and will address it in a future release.

Best,
Max
